# Generated by Django 4.1.3 on 2024-03-24 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_reservation_dropoff_car_car_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="amount",
        ),
    ]
